language: node_js
node_js:
- 4
- stable

deploy:
  provider: npm
  email: hello@trailsjs.io
  api_key:
    secure: i220oWG+yQsBbHz/AOy0DfB+Q2dvj3+PpY/kKEZ0Es9wS/4LxoTQRxlnkraQg/DOG2TFOiR0iwZ3nQZQj3hKzaCQsMm0vi1O189d/I0Sn9W62ZsExqPlxFOgDghgRBaPQ3wgtJudy18mehOItUi7UfRzbBOm8rpS1aqjThH0Me8bc76KzoCDATITB1VlfirFzhUJslh3GtmcThsf6YWK6jz9+QG5MdJCX8hxmcsYzsRjiLFoei1umvFFNjboewosh1g6GhaXoegfonbwRSMsCmtDN9Tq6RPSYGXIIRUA+KT1aMQWIfL06Hct4HxiOMMMoNgTJ5gIAGSjCTCYMCDRzdE5uUXO9A7SQK95bg64cnGpv1fLzyTp71yyooyW+HLa/WcOXZ2t4ldpjyYeuq6foyWot82ZPTPLWGvNOHwt5e7ni4OuCaPIzYGCNQ8S1jxDMDQ4Uq9i1Q+AGuMyxEoAV2aQZZMJ500JOnSsh5j+zKgIwewgX8vjDmlId94RW6bx9Jqnb8v80dza9QgdpgTh+Db1ka+ifDNVSzFHA2A2hEE1gFbWg657rlcYUtIsbwW0JytcSM1m2ghG3I88Xn4kiPzU4Gw9sp5M8UTyUh4PfynpXqgABSrLyRpfM5dfY0oK6A5/I1GRDzGBxQsjWZZbn1a22jj8LtKNQ8SscyIcaHo=
  on:
    tags: true
    repo: tjwebb/graphql-knex-resolver
